### PR TITLE
Adding all available aws regions to vpc tf module for dns suffix mapping

### PR DESCRIPTION
**Pull request by napcae**
Upon executing ```kraken cluster up```  I was greeted with the following error message:
```
TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Plan terraform configuration for current state of etcd] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["terraform", "plan", "-target", "module.vpc", "-target", "module.route53", "-target", "module.keypair", "-target", "module.subnet", "-target", "module.cluster_secgroup", "-target", "module.bastion", "-target", "module.etcd", "-input=false", "-no-color", "-out=/Users/napcae/.kraken/FDP/tf_plan"], "delta": "0:00:00.461502", "end": "2017-12-19 14:08:07.280109", "failed": true, "rc": 1, "start": "2017-12-19 14:08:06.818607", "stderr": "Errors:\n\n  * lookup: lookup failed to find 'eu-west-1' in:\n\n${lookup(var.dns_suffix, var.region)}", "stderr_lines": ["Errors:", "", "  * lookup: lookup failed to find 'eu-west-1' in:", "", "${lookup(var.dns_suffix, var.region)}"], "stdout": "There are warnings and/or errors related to your configuration. Please\nfix these before continuing.", "stdout_lines": ["There are warnings and/or errors related to your configuration. Please", "fix these before continuing."]}
```
Turns out kraken only supports US regions. This patch fixes that. I'm not very familiar with the codebase, I'd suggest updating more code should someone from the maintainer team knows where similar code exists.

### CODE REVIEW

**Comment by davidewatson** [comment]
Old `kraken` used to have [more dependencies](https://github.com/samsung-cnct/kraken-old/blob/a9c7896748e80c20863ef31d1e3b4f419407a41b/terraform/aws/variables.tf#L51) on the region and az's. I _think_ this might work though. Thanks!

**Comment by napcae** [comment]
CI fails because the VPCLimit is exceeded

```
 "stderr": "Error applying plan:\n\n1 error(s) occurred:\n\n* aws_vpc.vpc: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.\n\tstatus code: 400, request id: f95ea9f9-673f-4e54-87d8-189af4a8cae6\n\nTerraform does not automatically rollback in the face of errors.\nInstead, your Terraform state file has been partially updated with\nany resources that successfully completed. Please address the error\nabove and apply again to incrementally change your infrastructure.", 
```

**Comment by joejulian** [comment]
Argh. Someone will clean this up.

**Comment by davidewatson** [comment]
CI for AWS has been restarted after manually running the config generation stage.

**Comment by davidewatson** [comment]
This passed: https://git.cnct.io/common-tools/samsung-cnct_kraken-lib/pipelines/1344 but the GitHub status was not updated.

**Pull request merged**
