### PR TITLE
 changed defaults

### PR DESCRIPTION
**Pull request by guineveresaenger**
Added dns_only to deafults file

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Addresses https://github.com/samsung-cnct/kraken-lib/issues/904

**Comment by alejandroEsc** [comment]
@guineveresaenger can you also make the changes to the kraken_arguments.sh file:

```# pull in common utils
my_dir=$(dirname "${BASH_SOURCE}")
source "${my_dir}/common.sh"

DNS_ONLY=false
KRAKEN_DRYRUN=false```

i would like to see those defaults there always, and have the switch to true only when conditions are met. @coffeepac i dont think the case for nil on these variables really exists, so I dont expect this to be a tri-valued problem.

**Comment by guineveresaenger** [comment]
Hmmm, I do see your point @alejandroEsc

**Comment by alejandroEsc** [comment]
@guineveresaenger let's ask @joejulian then because the defaults in the bash to me take precedence of the defaults defined in the main.yaml file. I would like those removed if possible as the script should be the source of that truth.

**Comment by coffeepac** [comment]
@alejandroEsc I don't see a need to change how the variables are defaulted in the shell script.  right now, if you use the shell script to invoke the playbook things will work as expected.  the problem is that kraken isn't using the shell script. 

so, we need to make invoking the ansible directly work.

**Comment by alejandroEsc** [comment]
@coffeepac that is correct. However there is a ticket up about how kraken needs to be consistent about making calls to kraken-lib, which may mean call the scripts directly or keep just making calls to ansible. Depending on the choice we make we may need to make sure these vars are passed consistently or keep status quo. Either way, the issue still stands, as @guineveresaenger pointed out we have too many places were these things are happening.

**Comment by joejulian** [comment]
Right, since kraken bypasses the scripts the defaults need to be in kraken-lib's ansible defaults.

**Comment by coffeepac** [comment]
kraken doesn't always bypass the scripts, this is why the issue @alejandroEsc references exists.  my preference is we stop invoking ansible directly, but that's out of scope for this issue.

at the moment, if you use the script the variables are defaulted but not in the manner you suggest.  its a style preference.

**Comment by coffeepac** [comment]
anyway, any objections to me merging this as-is?

**Comment by guineveresaenger** [comment]
The test would currently object...

**Comment by alejandroEsc** [comment]
@coffeepac no objections, let's capture your comments about invoking ansible directly on the kraken ticket, ill post later. When the PR passes CI ill go ahead and merge it. Just wanted us all to be on the same page here.

**Pull request merged**
