### PR TITLE
kraken-tools version env variable for gitlab-ci file

### PR DESCRIPTION
**Pull request by leahnp**
fixes: https://github.com/samsung-cnct/kraken-lib/issues/1040

### CODE REVIEW

**Comment by coffeepac** [comment]
this PR (https://github.com/samsung-cnct/kraken-lib/pull/763/files) shows how this was being done in Jenkins land

**Comment by leahnp** [comment]
@coffeepac I was not understanding the scope before. Let me know if the latest commit looks more on track. Thank you.

**Comment by coffeepac** [comment]
looking better.  before, we only used the tagged version of kraken tools for the tagged releases of kraken-lib.  I think we want to keep that but I'm open to arguments.  

in the current PR we are using the tagged version of kraken-tools for all kraken-lib work

**Comment by leahnp** [comment]
@coffeepac let me know if the latest on this PR works.

**Pull request merged**
