### PR TITLE
[BAC-147] fix kraken-lib release process

### PR DESCRIPTION
**Pull request by coffeepac**
need to sort out why the command to re-write the dockerfile is failing.

EDIT:  the problem was that the dockerfile re-writing script was attempting to use `/bin/bash` which isn't present in docker image `docker:latest`.  We don't need anything in bash so I switched the shebang to sh.  script works now.

### CODE REVIEW

**Comment by coffeepac** [comment]
ready for merge

**Comment by philoserf** [comment]
as `#!/bin/bash` comes from our bash style guide. Perhaps variance from the style guide in a script should contain a justifying comment. That way our future selves will have the required context we built in this PR commentary.

**Comment by samba** [comment]
Agree w/ @philoserf ; however in CI containers, I'd also approve `apk add bash` as needed.

**Comment by coffeepac** [comment]
This isnt a container we build, we are using upstream docker.  

I can add a comment.

**Comment by samba** [comment]
Sorry, I meant to add that `apk add bash` command as part of the CI script, since we control which container it's running in, and that installation is pretty lightweight.

**Comment by coffeepac** [comment]
I would rather not mutate the container we are running in right now.  This is a break-fix and what we have in this PR right now works.  I would rather not sort out what changes may happen.

I can file an issue to handle making that change for later.

**Comment by coffeepac** [comment]
@samba or @philoserf I believe I have addressed all concerns and the latest commit has passed CI.  Can I get this merged?

**Comment by samba** [comment]
LGTM. Merging, even though I'm not actually listed as a reviewer etc...

**Pull request merged**
