### PR TITLE
only allow lowercase cluster names

### PR DESCRIPTION
**Pull request by leahnp**
GKE only allows lowercase letters.

This work was requested here: https://github.com/samsung-cnct/kraken/pull/211

### CODE REVIEW

**Comment by alejandroEsc** [comment]
is this change backwards compatible, if my cluster is already up will i be able to update?

**Comment by leahnp** [comment]
@alejandroEsc Good point - @coffeepac thoughts?

**Comment by coffeepac** [comment]
man, i feel like I've hit this before.  okay, no, we can't do it because it could cause existing clusters to break.

**Comment by alejandroEsc** [comment]
If this is a gke specific issue, im guessing clusters were not brought up with caps? if so then we can just go to that branch and make the validations there. If not, then further upstream we can check and make lower case all the names?

**Comment by leahnp** [comment]
I added some documentation about this to kraken - and if you TRY to spin up a GKE cluster you will see the error in this issue: https://github.com/samsung-cnct/kraken/issues/210

So it is pretty clear to the user what the problem is, just kind of annoying.

**Comment by alejandroEsc** [comment]
How about capturing the warning instead then and displaying it to the user.

**Comment by leahnp** [comment]
The warning is displayed to the user. Sorry if I wasn't clear about that.

**Pull request closed without merging**
