### PR TITLE
Only check etcd cluster-health for first node in each etcd nodePool (fixes #702).

### LINKED ISSUE #702: New etcd health check not quite correct
The full cluster check isn't quite correct.
```
- name: Wait for etcd cluster to form
  command: >
    ssh -o StrictHostKeyChecking=no
        -o UserKnownHostsFile=/dev/null
        -F {{ ssh_config }} {{ item.name }}-{{ idx }}
        etcdctl --ca-file={{ etcd_cafile }}
                --cert-file={{ etcd_certfile }}
                --key-file={{ etcd_keyfile }}
                --endpoints={{ etcd_loopback_endpoints }}
                   cluster-health
  register: etcd_result
  until: etcd_result | succeeded
  retries: "{{ etcd_retries }}"
  delay: "{{ etcd_delay }}"
  with_items: "{{ item.count }}"
  loop_control:
    loop_var: idx
  # See k2/674 for notes on the correct fix to eliminating this when statement.
  when: item.nodeConfig.providerConfig.enablePublicIPs is undefined or
        item.nodeConfig.providerConfig.enablePublicIPs
```

If it fails in the middle, it goes to the next index and overwrites the failure result.  i.e. if a later one is successful, then the whole thing is considered successful.

real example:
```
mikeln-bender:.kraken Mikel_Nelson$ ./zetcd.sh  mikeln-v17
Checking etcd cluster health ----------------------
Warning: Permanently added 'ec2-54-202-51-246.us-west-2.compute.amazonaws.com,54.202.51.246' (ECDSA) to the list of known hosts.
member ad5f68a1162ad52 is healthy: got healthy result from https://10.0.195.144:2379
member 4c9d0a2f0aabbba4 is healthy: got healthy result from https://10.0.160.121:2379
member 82063b34375c465d is healthy: got healthy result from https://10.0.99.188:2379
cluster is healthy
return 0
Warning: Permanently added 'ec2-54-202-177-220.us-west-2.compute.amazonaws.com,54.202.177.220' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint https://127.0.0.1:2379 exceeded header timeout
error #1: client: endpoint https://127.0.0.1:4001 exceeded header timeout

return 4
Warning: Permanently added 'ec2-34-210-85-122.us-west-2.compute.amazonaws.com,34.210.85.122' (ECDSA) to the list of known hosts.
member ad5f68a1162ad52 is healthy: got healthy result from https://10.0.195.144:2379
member 4c9d0a2f0aabbba4 is healthy: got healthy result from https://10.0.160.121:2379
member 82063b34375c465d is healthy: got healthy result from https://10.0.99.188:2379
cluster is healthy
return 0
Warning: Permanently added 'ec2-54-190-28-113.us-west-2.compute.amazonaws.com,54.190.28.113' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint https://127.0.0.1:2379 exceeded header timeout
error #1: client: endpoint https://127.0.0.1:4001 exceeded header timeout

return 4
Warning: Permanently added 'ec2-34-213-43-2.us-west-2.compute.amazonaws.com,34.213.43.2' (ECDSA) to the list of known hosts.
member ad5f68a1162ad52 is healthy: got healthy result from https://10.0.195.144:2379
member 4c9d0a2f0aabbba4 is healthy: got healthy result from https://10.0.160.121:2379
member 82063b34375c465d is healthy: got healthy result from https://10.0.99.188:2379
cluster is healthy
return 0
---------------------------------------------------
Checking etcdEvents cluster health ----------------
Warning: Permanently added 'ec2-54-244-15-166.us-west-2.compute.amazonaws.com,54.244.15.166' (ECDSA) to the list of known hosts.
member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381
member 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381
failed to check the health of member 5d18a7b3260b8d3d on https://10.0.209.47:2381: Get https://10.0.209.47:2381/health: dial tcp 10.0.209.47:2381: getsockopt: connection refused
member 5d18a7b3260b8d3d is unreachable: [https://10.0.209.47:2381] are all unreachable
member 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381
member 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381
cluster is healthy
return 0
Warning: Permanently added 'ec2-54-191-65-116.us-west-2.compute.amazonaws.com,54.191.65.116' (ECDSA) to the list of known hosts.
member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381
member 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381
failed to check the health of member 5d18a7b3260b8d3d on https://10.0.209.47:2381: Get https://10.0.209.47:2381/health: dial tcp 10.0.209.47:2381: getsockopt: connection refused
member 5d18a7b3260b8d3d is unreachable: [https://10.0.209.47:2381] are all unreachable
member 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381
member 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381
cluster is healthy
return 0
Warning: Permanently added 'ec2-54-187-128-201.us-west-2.compute.amazonaws.com,54.187.128.201' (ECDSA) to the list of known hosts.
member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381
member 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381
failed to check the health of member 5d18a7b3260b8d3d on https://10.0.209.47:2381: Get https://10.0.209.47:2381/health: dial tcp 10.0.209.47:2381: getsockopt: connection refused
member 5d18a7b3260b8d3d is unreachable: [https://10.0.209.47:2381] are all unreachable
member 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381
member 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381
cluster is healthy
return 0
Warning: Permanently added 'ec2-54-149-208-117.us-west-2.compute.amazonaws.com,54.149.208.117' (ECDSA) to the list of known hosts.
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2381: getsockopt: connection refused

return 4
Warning: Permanently added 'ec2-34-213-5-126.us-west-2.compute.amazonaws.com,34.213.5.126' (ECDSA) to the list of known hosts.
member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381
member 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381
failed to check the health of member 5d18a7b3260b8d3d on https://10.0.209.47:2381: Get https://10.0.209.47:2381/health: dial tcp 10.0.209.47:2381: getsockopt: connection refused
member 5d18a7b3260b8d3d is unreachable: [https://10.0.209.47:2381] are all unreachable
member 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381
member 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381
cluster is healthy
return 0
---------------------------------------------------
```

the ansible log for the same cluster:
```
TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Wait for etcd cluster to form] ***********************************
changed: [localhost] => (item=5)

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : debug] ***********************************************************
ok: [localhost] => {
    "etcd_result": {
        "changed": true,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_label": "5",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "attempts": 1,
                "changed": true,
                "cmd": [
                    "ssh",
                    "-o",
                    "StrictHostKeyChecking=no",
                    "-o",
                    "UserKnownHostsFile=/dev/null",
                    "-F",
                    "/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-v17/ssh_config",
                    "etcd-5",
                    "etcdctl",
                    "--ca-file=/etc/etcd/ssl/client-ca.pem",
                    "--cert-file=/etc/etcd/ssl/client.pem",
                    "--key-file=/etc/etcd/ssl/client-key.pem",
                    "--endpoints=https://127.0.0.1:2379,https://127.0.0.1:4001",
                    "cluster-health"
                ],
                "delta": "0:00:01.973300",
                "end": "2017-08-03 15:25:40.030213",
                "idx": "5",
                "invocation": {
                    "module_args": {
                        "_raw_params": "ssh -o StrictHostKeyChecking=no\n -o UserKnownHostsFile=/dev/null\n -F /Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-v17/ssh_config etcd-5\n etcdctl --ca-file=/etc/etcd/ssl/client-ca.pem\n --cert-file=/etc/etcd/ssl/client.pem\n --key-file=/etc/etcd/ssl/client-key.pem\n --endpoints=https://127.0.0.1:2379,https://127.0.0.1:4001\n cluster-health",
                        "_uses_shell": false,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "warn": true
                    }
                },
                "rc": 0,
                "start": "2017-08-03 15:25:38.056913",
                "stderr": "Warning: Permanently added 'ec2-34-213-43-2.us-west-2.compute.amazonaws.com,34.213.43.2' (ECDSA) to the list of known hosts.",
                "stderr_lines": [
                    "Warning: Permanently added 'ec2-34-213-43-2.us-west-2.compute.amazonaws.com,34.213.43.2' (ECDSA) to the list of known hosts."
                ],
                "stdout": "member ad5f68a1162ad52 is healthy: got healthy result from https://10.0.195.144:2379\nmember 4c9d0a2f0aabbba4 is healthy: got healthy result from https://10.0.160.121:2379\nmember 82063b34375c465d is healthy: got healthy result from https://10.0.99.188:2379\ncluster is healthy",
                "stdout_lines": [
                    "member ad5f68a1162ad52 is healthy: got healthy result from https://10.0.195.144:2379",
                    "member 4c9d0a2f0aabbba4 is healthy: got healthy result from https://10.0.160.121:2379",
                    "member 82063b34375c465d is healthy: got healthy result from https://10.0.99.188:2379",
                    "cluster is healthy"
                ]
            }
        ]
    }
}

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Fail if any etcd node failed to report healthy] ******************

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Pause when traditional etcd health checks are unavailable] *******

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : set_fact] ********************************************************
ok: [localhost]

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Wait for etcd cluster to form] ***********************************
changed: [localhost] => (item=5)

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : debug] ***********************************************************
ok: [localhost] => {
    "etcd_result": {
        "changed": true,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_label": "5",
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "attempts": 1,
                "changed": true,
                "cmd": [
                    "ssh",
                    "-o",
                    "StrictHostKeyChecking=no",
                    "-o",
                    "UserKnownHostsFile=/dev/null",
                    "-F",
                    "/Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-v17/ssh_config",
                    "etcdEvents-5",
                    "etcdctl",
                    "--ca-file=/etc/etcd/ssl/client-ca.pem",
                    "--cert-file=/etc/etcd/ssl/client.pem",
                    "--key-file=/etc/etcd/ssl/client-key.pem",
                    "--endpoints=https://127.0.0.1:2381",
                    "cluster-health"
                ],
                "delta": "0:00:02.163011",
                "end": "2017-08-03 15:25:42.601724",
                "idx": "5",
                "invocation": {
                    "module_args": {
                        "_raw_params": "ssh -o StrictHostKeyChecking=no\n -o UserKnownHostsFile=/dev/null\n -F /Users/Mikel_Nelson/dev/cloud/k2new/myconfig/.kraken/mikeln-v17/ssh_config etcdEvents-5\n etcdctl --ca-file=/etc/etcd/ssl/client-ca.pem\n --cert-file=/etc/etcd/ssl/client.pem\n --key-file=/etc/etcd/ssl/client-key.pem\n --endpoints=https://127.0.0.1:2381\n cluster-health",
                        "_uses_shell": false,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "warn": true
                    }
                },
                "rc": 0,
                "start": "2017-08-03 15:25:40.438713",
                "stderr": "Warning: Permanently added 'ec2-34-213-5-126.us-west-2.compute.amazonaws.com,34.213.5.126' (ECDSA) to the list of known hosts.",
                "stderr_lines": [
                    "Warning: Permanently added 'ec2-34-213-5-126.us-west-2.compute.amazonaws.com,34.213.5.126' (ECDSA) to the list of known hosts."
                ],
                "stdout": "member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381\nmember 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381\nmember 5d18a7b3260b8d3d is unreachable: no available published client urls\nmember 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381\nmember 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381\ncluster is healthy",
                "stdout_lines": [
                    "member ba2c6492e82fb5 is healthy: got healthy result from https://10.0.105.24:2381",
                    "member 1bf473e19954e364 is healthy: got healthy result from https://10.0.52.230:2381",
                    "member 5d18a7b3260b8d3d is unreachable: no available published client urls",
                    "member 68a55ffda61db739 is healthy: got healthy result from https://10.0.217.238:2381",
                    "member 9510bebdae52fd57 is healthy: got healthy result from https://10.0.104.55:2381",
                    "cluster is healthy"
                ]
            }
        ]
    }
}

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Fail if any etcd node failed to report healthy] ******************

TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Pause when traditional etcd health checks are unavailable] *******
```

Note that both clusters were considered healthy, even though etcdEvent-1,3 and etcd-2,4 are dead.

### PR DESCRIPTION
**Pull request by davidewatson**
…fixes #702).

### CODE REVIEW

**Comment by davidewatson** [comment]
@leahnp: This is the code I had for #702. It may be obsolete once your changes are ready, hence the DO_NOT_MERGE label.

**Comment by leahnp** [comment]
Copy that - thanks!

**Comment by davidewatson** [comment]
Once #858 is merged I will revisit this. I think if two clusters are formed then `cluster-health` should fail, but I have doubts about the reliability of SRV records as a method of determining the expected cluster size, so you may be right.

**Comment by davidewatson** [comment]
Closing in favor of #931

**Pull request closed without merging**
